name: Deploy mainnet frontend

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm ci

      - name: Build smart contracts
        run: npm run build -- --all

      - name: Build frontend
        run: node scripts/ci-build-frontend-for-mainnet.js

      - name: Deploy (must be published manually in Netlify UI)
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=frontend/dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_MAINNET_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
