name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: npm ci

      - run: npm run lint

      - name: Setup frontend for testnet
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/testnet' }}
        run: node scripts/ci-setup-frontend-for-testnet.js

      - name: Setup frontend for mainnet
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
        run: node scripts/ci-setup-frontend-for-mainnet.js

      - name: Build smart contracts
        run: npm run build -- --all

      - run: npm run build:frontend

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: frontend/dist/
          retention-days: 1

  deploy-testnet:
    name: Deploy testnet frontend
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/testnet' }}

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: frontend/dist

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=frontend/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TESTNET_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy-mainnet:
    name: Deploy mainnet frontend
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: frontend/dist

      - name: Deploy (must be published manually in Netlify UI)
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=frontend/dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_MAINNET_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
