name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: npm ci

      - run: npm run lint

      - name: Setup frontend for testnet
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/testnet' }}
        run: node scripts/ci-setup-frontend-for-testnet.js

      - name: Setup frontend for mainnet
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
        run: node scripts/ci-setup-frontend-for-mainnet.js

      - name: Build smart contracts
        run: npm run build -- --all

      - run: npm run build:frontend
      
      - name: Netlify Preview URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "This pull request is being automatically deployed to Netlify.\n\n🔍 Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}\n✅ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false

      - name: Deploy testnet frontend
        uses: netlify/actions/cli@master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/testnet' }}
        with:
          args: deploy --dir=frontend/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TESTNET_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy mainnet frontend (must be published manually in Netlify UI)
        uses: netlify/actions/cli@master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
        with:
          args: deploy --dir=frontend/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_MAINNET_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
