name: Promote Test To Prod (Frontend Only)

on: workflow_dispatch

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        ref: testnet

      - name: Merge test -> prod
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          force: true